### ISSUE TITLE
Value assignments to attributes excluded for entity are silently ignored

### ISSUE THREAD

**Issue by IwoHerka** [jazzband/django-eav2#11]
Overriding `EavConfig` class when registering `Entity` allows the end-user to limit attributes which are "visible" to the `Entity` instance (registered model):

```
class SuppliersEavConfig(EavConfig):
    @classmethod
    def get_attributes(cls):
        return Attribute.objects.filter(slug__contains='a')
```

This causes assignments such as:

```
supplier.eav.height = 3
```
to be _silently_ ignored upon save.

This a useful feature, however, arguably, the whole point is to disallow certain assignments. Therefore,
if an assignment takes place, it is safe to assume that something went wrong and validation should scream, like it normally does.

What do you think? @maticomp @dragonee 
If there are no objections, I will make issue for the fix.

**Comment by dragonee** [comment]
No objections to throwing an error. In the long discussion we analyzed edge-edge cases, however after further looking it up, all the cases will be satisfied:

1) EAV Form will set only the valid attributes on model. In implies that without a specific code in the application there's no way to trigger this error (a form would never display invalid attributes and further on, will not set them on the model on save - two-step checking). It means that a form with entity that has limited attribute set will IGNORE the form data for invalid attributes even if it was present (e.g. dynamic JS form field generation), which preserves the law that forms should only care for the input directly regarded by them.

2) However, if a specific code in the application sets invalid attributes on the code, a `ValidationError` will be thrown, which is a very useful behaviour if a programmer overlooked some change that should be made. This `ValidationError` is thrown in `save()`, so it will propagate and most probably generate a 500 error, unless a programmer manually will put the code in the `try` block.

A suggestion - when the error is thrown, please look the attribute up in the database and throw two different messages:

- Attribute X is not permitted by the EntityClass config's get_atttribute() implementation.
- Attribute X does not exist.
