### ISSUE TITLE
Consider adding model validation to Entity

### ISSUE THREAD

**Issue by dragonee** [jazzband/django-eav2#14]
Some `ValidationError`s thrown in entity's `save()` method are user preventable, for example:
1) EAV field cannot be blank
2) %(enum)s is not a valid choice
3) There are also custom Attribute validators.

In addition to having them as the last-resort validation in the `save()` method, these could also be added to Django's model clean methods in order to make the errors visible to the user on form save:
https://docs.djangoproject.com/en/2.0/ref/models/instances/#validating-objects

In case that the current validation works (i.e. does not throw 500 errors in the django admin or test form), the question is - how was that implemented? ValidationErrors are not catched in Django after `is_valid()` finishes.

**Comment by dragonee** [comment]
So what really happens in the case I mangle the POST data and put an eav choice value that is not valid?

**Comment by IwoHerka** [comment]
You get a `ValidationError`, like you normally would. It's just thrown from `pre_save_handler` and not `clean_fields`.
