### ISSUE TITLE
Doesn't work with models with UUIDs as primary keys

### ISSUE THREAD

**Issue by Ptosiek** [jazzband/django-eav2#31]
Hi,
Issue is originally from django-eav but as you seem more active on this fork:
The Value model uses an IntegerField as the entity_id part of the GFK to the entity object. That doesn't work if the PK of the entity model is a UUIDField.
Using a CharField instead solves it but comes with its counterparts for postgres, see:
https://code.djangoproject.com/ticket/16055

**Comment by IwoHerka** [comment]
Hi, thanks for the submission. I will look into that.

**Comment by maticomp** [comment]
@xnegativx thanks for reporting this issue! We thought this might happen.

I think using CharField to store generic foreign keys, while possibly solving the issue on the surface, is a hack that can bring more issues down the road. Official Django docs mention using CharFields or TextFields as a viable solution for generic foreign keys with inconsistent types, but you've already mentioned issues with casting datatypes on postgres and I assume more edge cases may surface if we choose to go this route.

What I think we could possibly do, though it's not a simple fix, is implement swappable model for values and use proper inheritance to define matching type foreign keys. This also comes with other costs.

I'm leaving this open for further discussion and parking it until next project milestone. As soon as we finish the re-release milestone with housekeeping, docs and such, I'll dig deeper into this issue.

**Comment by Dresdn** [comment]
#38 was a duplicate. Closed via #89
