### ISSUE TITLE
Make it possible to have Attributes only apply to one model

### ISSUE THREAD

**Issue by tykling** [jazzband/django-eav2#40]
## Detailed Description
Sometimes it would be handy to be able to limit Attributes to only one model. I would add an optional FK from Attribute to ContentType, like there already is on the Value table.

## Context
How would I use this? Well say I have a model called Car and another called Movie. The Attribute "color" makes sense for Car instances, but not for Movie instances. With the Attribute "duration" it is the other way around; it makes sense for Movie instances, but not for Car instances.

## Possible Implementation
See https://github.com/tykling/django-eav2/commit/dd278360f4f76002182a03354fee0fb959f386e7
Let me know if you want a PR

**Comment by IwoHerka** [comment]
@tykling Thanks for the proposition, we would gladly accept a PR.

**Comment by farhah** [comment]
I really appreciate it if this is merged into the current release. I have the same requirements as well.

**Comment by farhah** [comment]
eav/registry.py
I only need to add 1 line into the eav/registry.py

`setattr(config_cls, 'caller_model', instance)`

```
    @staticmethod
    def attach_eav_attr_caller_model(sender, *args, **kwargs):
        """
        Attach EAV Entity toolkit to an instance after init.
        """
        instance = kwargs['instance']
        config_cls = instance.__class__._eav_config_cls
        setattr(instance, config_cls.eav_attr, Entity(instance))
        setattr(config_cls, 'caller_model', instance)

    def _attach_signals(self):
        """
        Attach pre- and post- save signals from model class
        to Entity helper. This way, Entity instance will be
        able to prepare and clean-up before and after creation /
        update of the user's model class instance.
        """
        post_init.connect(Registry.attach_eav_attr_caller_model, sender = self.model_cls)
        pre_save.connect(Entity.pre_save_handler, sender = self.model_cls)
        post_save.connect(Entity.post_save_handler, sender = self.model_cls)


    def _detach_signals(self):
        """
        Detach all signals for eav.
        """
        post_init.disconnect(Registry.attach_eav_attr_caller_model, sender = self.model_cls)
        pre_save.disconnect(Entity.pre_save_handler, sender = self.model_cls)
        post_save.disconnect(Entity.post_save_handler, sender = self.model_cls)
```


so that I can call caller_model from class ActivityEavConfig(EavConfig):

```
class ActivityEavConfig(EavConfig):

    @classmethod
    def get_attributes(cls):
        """
        By default, all :class:`~eav.models.Attribute` object apply to an
        entity, unless you provide a custom EavConfig class overriding this.
        """
        registered_attrs = RegisterActivityAttr.objects.filter(activity_type=cls.caller_model.activity_type)
        attrs = list()
        for attr in registered_attrs:
            attrs.append(attr.eav_attribute.id)

        return Attribute.objects.filter(pk__in=attrs)
```

What do you think of this implementation? Is there better way to get the calling model instance other than this way?
