### ISSUE TITLE
Filtering object types

### ISSUE THREAD

**Issue by radalin** [jazzband/django-eav2#48]
I'm trying to filter based on the object type. Usage for "simple" attributes are like this:
```
MyModel.objects.filter(eav__custom_attr=2)
```
However when using the same notation for objects:
```
MyModel.objects.filter(eav__custom_obj=2)
```
It throws the following error:
```
Field 'value_object' does not generate an automatic reverse relation and therefore cannot be used for reverse querying. If it is a GenericForeignKey, consider adding a GenericRelation.
```

## Expected Behavior
Usage of the following lines should provide a list of filtered objects
```
MyModel.objects.filter(eav__custom_obj=2)
```

## Actual Behavior
Throws an exception.

## Possible Fix
Syntax of how this can be done can be added to the readme if it's possible (or it could say it's not supported yet).

Something like this can be implemented:
```
MyModel.objects.filter(eav__custom_obj__pk=2)
```

## Your Environment

* Version used: 0.13.0
* Environment name and version: Django 2.2.2, Python 3.7.5
* Operating System and version: Mac OS

**Comment by radalin** [comment]
I have created a PR for this. I'm not sure if this is a correct way to do it but it solves the problem I encountered above.

**Comment by DanielIndictor** [comment]
Sorry it took so long to address this. Thank you for your PR. It has been merged.
