### ISSUE TITLE
how to access attribute fields properties in BaseDynamicEntityForm?

### ISSUE THREAD

**Issue by fcoppey** [jazzband/django-eav2#53]
I have a form for my model Sample which contains attributes:

```
class SampleForm(BaseDynamicEntityForm):
    def __init__(self, *args, **kwargs):
        self.request_user = kwargs.pop('request_user')
        self.sample = kwargs.pop('sample')
        kwargs.setdefault('label_suffix', '')
        super(SampleForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Sample
        fields = [
            'name',
        ]
```

I would like to override the choices of one of my eav attributes which is a Multiple Choice in order to show only part of the choices depending on the user.

with the normal forms.ModelForm I could define the field choices in my __init__ function with:
self.fields['eav_attribute_name'].choices = choices_subset

but it does not work with BaseDynamicEntityForm. 

Any suggestion?

thanks a lot for the great work.

same thing I would like to show only some of the attributes in the form depending on the user or on other properties of the main object sample. How could I?

**Comment by fcoppey** [comment]
can someone help me? I'm a bit lost ... sorry

**Comment by fcoppey** [comment]
hello... I still couldn't figure this out and I'm blocked because I would like to change the choices in a form with eav attrributes depending on the user... with a normal form I would simply use self.fields['myfield'].choices = my_choices but how can I do that with eav attributes?

Hope someone can guide me. thanks for the amazing work!

**Comment by DanielIndictor** [comment]
Can you post some error messages and a minimum reproducible example to help me debug? I'd be glad to help.

(if you solve this on your own a PR would be much appreciated)

**Comment by fcoppey** [comment]
Thanks for your reply,

It’s not really a bug or an error… I just don’t understand how to access and modify eav form field properties in order to modify their initial value or the list of choices for instance.

Here is my normal form class to edit the field “name" of the objects from my model Sample:

class SampleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request_user = kwargs.pop('request_user')
        self.sample = kwargs.pop('sample')
        kwargs.setdefault('label_suffix', '')
        super(SampleForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Sample
        fields = [
            'name',
        ]

        help_texts = {
            'name': _('If you type a sample name that already exists in the database the measures from this sample will be transfered to the existing sample and aggregated.'),
        }


Now if I want to show in my form the eav attributes of my object Sample along with the field “name” of the sample I simple change the SampleForm argument from forms.ModelForm to BaseDynamicEntityForm.

Then I see all the eav attributes in the form. Now my question is how can I adjust some parameters from my eav attributes form fields in the SampleForm class? For example, If I want to change the initial value of my field “name” from the model Sample I can simply add in the __inti__ function :  self.fields[’name’].initial = “my_initial_value”.

How can I set this parameter for eav fields?, I was thinking I could do something like : self.eav.fields[‘my_attribute’].initial = “my_attribute_initia_value”.

I hope this time is more clear :-)

Thanks a lot

Florentin

On 18 Aug 2020, at 23:01, Daniel Indictor <notifications@github.com<mailto:notifications@github.com>> wrote:



Can you post some error messages and a minimum reproducible example to help me debug? I'd be glad to help.
