### ISSUE TITLE
DRF support

### ISSUE THREAD

**Issue by jayvdb** [jazzband/django-eav2#55]
It would be great if there was a generic/basic DRF implementation provided here, perhaps as "contrib" if not core.

It would be wise to avoid design it so that it is usable by everyone, but it would outline the structure to follow for people that needed to create their own more specialised one, and probably provide some of the classes they need.

If interested, I have a basic DRF implementation which isnt generic yet, but it wouldnt be too difficult for me to split off the custom bits to create a generic implementation.

**Comment by DanielIndictor** [comment]
Sure I'd be happy to review the code.
