### ISSUE TITLE
NullBooleanField is deprecated

### ISSUE THREAD

**Issue by zachtaylor21** [jazzband/django-eav2#56]
Provide a general summary of the issue in the title above.
Django 3.1.2 gives a deprecation warning when running the `eav.0001_initial` migration:

> eav.Value.value_bool: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
>        HINT: Use BooleanField(null=True) instead.

## Expected Behavior
Shouldn't get deprecation warning

## Actual Behavior
Got deprecation warning

## Possible Fix
Replace `NullBooleanField` with `BooleanField(null=True)` as the deprecation warning recommends.

## Steps to Reproduce
1) Install Django 3.1.2
2) Install django-eav2
3) Add `'eav'` to `INSTALLED_APPS`
4) Run `python manage.py migrate`.

## Your Environment
Linux, using Django 3.1.2

* Version used: 0.13.0
* Environment name and version (e.g. Django 2.0.4, pip 9.0.1): Django 3.1.2
* Operating System and version: Ubuntu 18.04
* Link to your project (if applicable):

**Comment by fcoppey** [comment]
iS this package still actively maintained or not?

just to know if it's recommended to use it... 

Thanks
