### ISSUE TITLE
get_values() and get_values_dict() returns different type for enum

### ISSUE THREAD

**Issue by fcoppey** [jazzband/django-eav2#61]
why not returning the value of the enum element in get_values()? so that we have a dictionary that ca be used to print attributes easily?
 As of now I need to always test for enum element in my templates:
{% for obj in sample.eav.get_values %}
            <span class="sample-attributes-title">{{ obj.attribute.name }}:</span>{% if obj.value.value %}{{ obj.value.value }}{% else %}{{ obj.value }}{% endif %}</div>
        {% endfor %}

Am I missing something?

**Comment by Dresdn** [comment]
I know this is super late, but that's pretty much what `get_values_dict()` does.

Additionally, I did just redo the `str()` and `repr()` results, so you can now nicely print `{{ obj.value }}`
