### ISSUE TITLE
0.13 to master fails - django.db.utils.ProgrammingError: relation "eav_attribute_entity_ct" does not exist

### ISSUE THREAD

**Issue by Dresdn** [jazzband/django-eav2#62]
Provide a general summary of the issue in the title above.

Moving from the latest tag (0.13) to the master branch breaks with:

```
django.db.utils.ProgrammingError: relation "eav_attribute_entity_ct" does not exist
LINE 1: ...pe"."model" FROM "django_content_type" INNER JOIN "eav_attri...
```

This is related to #59 where the migration to create the `entity_ct` field isn't executed as the `0001_initial` migration already executed.

## Expected Behavior
Field `entity_ct` to be created by migration.

## Actual Behavior
Migration isn't executed.

## Possible Fix
Create a proper migration - PR coming.

## Steps to Reproduce
1. Install latest tag
2. Upgrade to head

## Your Environment
Include relevant details about the environment you experienced the bug in.

* Version used:
* Environment name and version (e.g. Django 2.0.4, pip 9.0.1): Django 3.1.5
* Operating System and version:
* Link to your project (if applicable):

**Comment by lvm** [comment]
Looks like this was fixed here: https://github.com/lvm/django-eav2/pull/63
