### ISSUE TITLE
0.14.0 on pypi

### ISSUE THREAD

**Issue by kolhir** [jazzband/django-eav2#67]
Hello, when will the release  0.14.0 be on pypi?

**Comment by lvm** [comment]
Hi, i just started maintaining this project after being abandoned. Any help with open issues would be greatly appreciated, until then, i can only ask for patience :-)

In the meantime you could try installing directly from the master branch, all tests are passing. Keep in mind that it's only compatible with Django >= 3.1 this time.

**Comment by Melevir** [comment]
Any news here? I'll be glad to help with the release if you need assistance :)

**Comment by lvm** [comment]
Nope, sorry. If you can get Iwo Herka (@IwoHerka) to reply to this issue, so i can have access to the pypi project[0], that would make things easier for all.

[0] https://pypi.org/project/django-eav2/

**Comment by Dresdn** [comment]
@lvm - What about opening a PEP 541 request over at https://github.com/pypa/pypi-support/issues/new/choose?

See https://github.com/pypa/warehouse/issues/9412 for reference

**Comment by lvm** [comment]
hi @Dresdn 

@DanielIndictor kindly gave me access to pypi, I just didn't had the time these days to work on it. I'll make a couple of changes to this project so we can stop worrying about these bottlenecks.

**Comment by Dresdn** [comment]
Good stuff! Appreciate the work!

**Comment by lvm** [comment]
@kolhir @Melevir @Dresdn 

As you can see, i transfered this project over to [Jazzband](https://jazzband.co/), so for future maintenance everyone can join this team and take care of this project as a group. 

I'll be closing some issues detailed here: https://github.com/jazzband/django-eav2/issues/69
Any help is appreciated.

Regards,
@lvm

**Comment by Dresdn** [comment]
Closing out as release process has been worked out, and [Version 1.0.0](https://pypi.org/project/django-eav2/) is up!
