### ISSUE TITLE
TypeError __init__() got an unexpected keyword argument 'max_length'

### ISSUE THREAD

**Issue by PUYUP** [jazzband/django-eav2#74]
Provide a general summary of the issue in the title above.

## Expected Behavior
Show add attribute value form

## Actual Behavior
Return `TypeError __init__() got an unexpected keyword argument 'max_length'`

## Possible Fix
Not obligatory, but you can suggest a fix or reason for the bug.

## Steps to Reproduce
Just install v0.14.0 then open admin page navigate to EAV -> Value -> Add

## Your Environment
Include relevant details about the environment you experienced the bug in.

* Version used: 0.14.0
* Environment name and version: Django 3.2.7
* Operating System and version: Windows 10

**Comment by Dresdn** [comment]
Merged in #75
