### ISSUE TITLE
Consider adding pre-commit.yml

### ISSUE THREAD

**Issue by lvm** [jazzband/django-eav2#76]
## Detailed Description

This issue is to add pre-commit.yml hooks to this project.
There are a few that I think can be interesting:

*  github.com/ecugol/pre-commit-hooks-django  (as the name suggests...)
*  github.com/psf/black (runs `black` on the project)
* github.com/pre-commit/pre-commit-hooks (plus a bunch from this default repo)

## Context

This is relevant since it has been enabled automatically in all jazzband repos. 

## Possible Implementation

There's a discussion in the jazzband orga about this: https://github.com/orgs/jazzband/teams/members/discussions/18

**Comment by Dresdn** [comment]
I think this is a good idea. On that line of thinking, some extra steps we can add to the [Run Tests](https://github.com/jazzband/django-eav2/blob/master/.github/workflows/test.yml#L43) portion could be:

```
poetry run flake8 .
poetry run mypy eav
poetry run doc8 -q docs
poetry run safety check --full-report
poetry run python manage.py makemigrations --dry-run --check
poetry run safety check --full-report 
```

plus others.

The steps are there, but I wouldn't run flake8 or mypy just yet as there's too many errors.

**Comment by Dresdn** [comment]
I tried to add [pre-commit-hooks-django](github.com/ecugol/pre-commit-hooks-django) but between the dependency not installing and it unable to handle HEAD for some reason, I abandoned it.
