### ISSUE TITLE
Set up CI for Jazzband project releases if needed and open ticket if yes

### ISSUE THREAD

**Issue by Dresdn** [jazzband/django-eav2#84]

**Comment by jezdez** [comment]
Fixed in a303c841ff880d9be098d3ecc0e74de745d3e7c4.

**Comment by Dresdn** [comment]
Thanks @jezdez.

Purely out of curiosity, since the package uses poetry, couldn't the workflow just use poetry to publish natively? Rather than use a different workflow and another package, I was going to commit:

```
- name: Build package
        run: |
          poetry build

      - name: Upload packages to Jazzband
        run: |
          poetry config repositories.jazzband https://jazzband.co/projects/django-eav2/upload
          poetry config http-basic.jazzband jazzband ${{ secrets.JAZZBAND_RELEASE_KEY }}
          poetry publish -r jazzband
```

**Comment by jezdez** [comment]
@Dresdn In theory yes, but the Jazzband package index isn't tested with Poetry's upload system so I can't be sure if it'll work, there may be subtle differences in behavior.

I have half-done plans to replace the custom GitHub Actions workflow we use throughout the Jazzband org with own GitHub actions (now that there is support for [composite actions](https://github.com/actions/runner/issues/646#issuecomment-901336347)) that wrap the PyPA action or in this case call the standard commands for Poetry as you describe above. But that's not possible just yet.

Here's how the `release.yml` would look like:

 ```
name: Release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jazzband/actions/release-poetry@v1
```

**Comment by Dresdn** [comment]
Good to know. Thanks!
