### ISSUE TITLE
does not work if type entity_id is uuid

### ISSUE THREAD

**Issue by malikov73** [jazzband/django-eav2#95]
<img width="630" alt="Снимок экрана 2021-10-27 в 13 07 27" src="https://user-images.githubusercontent.com/36269456/139045588-85aff781-03b2-4a88-903f-565ebece4a3e.png">

**Comment by Dresdn** [comment]
Duplicate of #31 and #38 and was fixed in #89

If you can't build from source, I'll put a new release out this week.
